{"name": "test_login_0_failed_wrong_datas[data3]", "status": "passed", "attachments": [{"name": "log", "source": "6fc27159-782d-43f4-99c8-8b92e56d13be-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '186847055311', 'passwd': 'python', 'check': '请输入正确的手机号'}"}], "start": 1608217605167, "stop": 1608217605357, "uuid": "f83f1712-ea24-4d4f-909d-3119f32a235c", "historyId": "39d42cf2c7c141d97498c560376ba8de", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "7508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}