{"name": "test_login_0_failed_wrong_datas[data2]", "status": "passed", "attachments": [{"name": "log", "source": "0634de88-8aec-4805-84c9-9d346a47f609-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '186847', 'passwd': 'python', 'check': '请输入正确的手机号'}"}], "start": 1608299394058, "stop": 1608299394241, "uuid": "52eb17ab-0ac3-466c-9142-ab62ae778581", "historyId": "68cf2b0989aa4e51d177a21c2d251b6c", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "59000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}