{"name": "test_login_0_failed_wrong_datas[data2]", "status": "passed", "attachments": [{"name": "log", "source": "837d7394-a223-4caa-8621-1c14f1e9fb0b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '186847', 'passwd': 'python', 'check': '请输入正确的手机号'}"}], "start": 1608298462923, "stop": 1608298463162, "uuid": "b6fea3d2-a556-48d0-ae21-54de251965b7", "historyId": "68cf2b0989aa4e51d177a21c2d251b6c", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "59848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}