{"name": "test_login_0_failed_wrong_datas[data1]", "status": "passed", "attachments": [{"name": "log", "source": "87e81398-4532-4b32-98b3-66ae24f09ff7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '', 'passwd': 'python', 'check': '请输入手机号'}"}], "start": 1608217604051, "stop": 1608217604522, "uuid": "0398550a-109a-4cab-a8b2-c35a95bfa181", "historyId": "50b62d68a5c78b16f277d604e09ea628", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "7508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}