{"name": "test_login_0_failed_wrong_datas[data2]", "status": "passed", "attachments": [{"name": "log", "source": "7b88f681-2f66-4eea-bf78-9efebf6398b9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '186847', 'passwd': 'python', 'check': '请输入正确的手机号'}"}], "start": 1608218581812, "stop": 1608218582374, "uuid": "fd035768-0a17-4dbb-a9c9-a6528a3cf916", "historyId": "68cf2b0989aa4e51d177a21c2d251b6c", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "39100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}