{"name": "test_login_0_failed_wrong_datas[data3]", "status": "passed", "attachments": [{"name": "log", "source": "9f32297d-d17b-42f0-aa6a-e5008f826a05-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '186847055311', 'passwd': 'python', 'check': '请输入正确的手机号'}"}], "start": 1608298463604, "stop": 1608298463862, "uuid": "991b4824-a8da-4350-8a08-7f10ff1914ad", "historyId": "39d42cf2c7c141d97498c560376ba8de", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "59848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}