{"name": "test_login_0_failed_wrong_datas[data3]", "status": "passed", "attachments": [{"name": "log", "source": "c405b3d6-bd1e-4ef8-8997-16b1bc46777f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '186847055311', 'passwd': 'python', 'check': '请输入正确的手机号'}"}], "start": 1608217368715, "stop": 1608217368983, "uuid": "c1f3780f-c176-44d5-9921-b8c21de92a9e", "historyId": "39d42cf2c7c141d97498c560376ba8de", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "56724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}