{"name": "test_login_0_failed_wrong_datas[data3]", "status": "passed", "attachments": [{"name": "log", "source": "c92d9ea7-b807-4925-b093-8b13c64b96d2-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c10625b9-e41f-450d-ad27-d64fce30f670-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '186847055311', 'passwd': 'python', 'check': '请输入正确的手机号'}"}], "start": 1608132624399, "stop": 1608132624669, "uuid": "22fb917a-e59a-4e51-8508-b764cee0ac8c", "historyId": "39d42cf2c7c141d97498c560376ba8de", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "53180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}