{"name": "test_login_0_failed_wrong_datas[data3]", "status": "passed", "attachments": [{"name": "log", "source": "080e9561-4017-44cf-8f03-b6536b6ce586-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '186847055311', 'passwd': 'python', 'check': '请输入正确的手机号'}"}], "start": 1608299394432, "stop": 1608299394615, "uuid": "0153f2c4-b8e1-4465-b879-68851899010b", "historyId": "39d42cf2c7c141d97498c560376ba8de", "testCaseId": "735933ecd585cb26d239d15346a80fa1", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_0_failed_wrong_datas", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "59000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}